includes:
- ./includes/settings/tk-animate.yml
- ./includes/settings/tk-premiere.yml
- ./includes/settings/tk-illustrator.yml

engines:
  tk-animate: "@settings.tk-animate.asset_step"
  tk-premiere: "@settings.tk-premiere.asset_step"
  tk-illustrator: "@settings.tk-illustrator.asset_step"

