# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

################################################################################

includes:
- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
- ./tk-multi-shotgunpanel.yml
- ./tk-multi-workfiles2.yml

################################################################################

# asset
settings.tk-animate.asset:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.animate"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.animate"
  shelf_favorites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: '@engines.tk-animate.location'

# asset_step
settings.tk-animate.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-loader2: "@settings.tk-multi-loader2.animate"
    tk-multi-publish2: "@settings.tk-multi-publish2.animate.asset_step"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.animate"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.animate.asset_step"
  shelf_favorites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  location: '@engines.tk-animate.location'

# project
settings.tk-animate.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.animate"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.animate"
  shelf_favorites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  location: '@engines.tk-animate.location'

# shot
settings.tk-animate.shot:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.animate"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.animate"
  shelf_favorites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  location: '@engines.tk-animate.location'

# shot_step
settings.tk-animate.shot_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-loader2: "@settings.tk-multi-loader2.animate"
    tk-multi-publish2: "@settings.tk-multi-publish2.animate.shot_step"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.animate"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.animate.shot_step"
  shelf_favorites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  location: '@engines.tk-animate.location'
