################################################################################

# ---- Animate

# asset step
settings.tk-multi-publish2.animate.asset_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: animate_asset_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: animate_asset_publish
  - name: Upload for review
    hook: "{self}/upload_version.py:{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings:
        Movie Output Module: Lossless with Alpha
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

# shot_step
settings.tk-multi-publish2.animate.shot_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: animate_shot_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: animate_shot_publish
  - name: Upload for review
    hook: "{self}/upload_version.py:{engine}/tk-multi-publish2/basic/upload_version.py"
    settings:
        Movie Output Module: Lossless with Alpha
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

################################################################################

# ---- Premiere

# asset step
settings.tk-multi-publish2.premiere.asset_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: premiere_asset_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: premiere_asset_publish
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

# shot_step
settings.tk-multi-publish2.premiere.shot_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: premiere_shot_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: premiere_shot_publish
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

################################################################################

# ---- illustrator

# asset step
settings.tk-multi-publish2.illustrator.asset_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: illustrator_asset_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: illustrator_asset_publish
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

# shot_step
settings.tk-multi-publish2.illustrator.shot_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: illustrator_shot_work
  publish_plugins:
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to ShotGrid
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_document.py"
    settings:
        Publish Template: illustrator_shot_publish
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

